config/routes.rb
Rails.application.routes.draw do

  #pages
  root "pages#welcome"
  get '/about' => 'pages#about'
  get '/contact' => 'pages#contact'

  #games
  resources :games do
    resources :reviews, only: [:new, :create, :edit, :update]
  end

  #users
  resources :users
  get '/signup' => 'users#new', as: :signup
  get '/users/:id/games' => 'users#games', as: :user_games
  patch '/users/:id/photo' => 'users#photo', as: :user_photo

  #sessions
  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout

  #search
  get '/search' => 'search#results'

  #password resets
  resources :password_resets


end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include ActiveModel::SecurePassword
  
  field :first_name, type: String
  field :last_name, type: String
  field :email, type: String
  field :password_digest, type: String
  field :games_played, type: Array, default: []
  field :games_playing, type: Array, default: []
  field :games_want, type: Array, default: []
  mount_uploader :photo, PhotoUploader
  has_and_belongs_to_many :games
  has_many :reviews

  has_secure_password

  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: true

  def get_list_location(game)
    if self.games_played.include?(game.id.to_s)
      return :games_played
    elsif self.games_playing.include?(game.id.to_s)
      return :games_playing
    elsif self.games_want.include?(game.id.to_s)
      return :games_want
    else
      return nil
    end
  end

  def average_rating
    if self.reviews.count == 0
      return 0
    else
      total = 0
      self.reviews.each do |review|
        total += review.rating
      end
      return (total.to_f / self.reviews.count).round(2)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorize, only: [:show, :games, :update]

  def show
    @user = User.find(params[:id])
  end


  def new
    redirect_to games_path if current_user
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id.to_s
      redirect_to user_path(@user)
    else
      flash.now[:danger] = @user.errors.full_messages.to_sentence
      render :new
    end
  end

  def photo
    @user = User.find(params[:id])
    @user.update(params.require(:user).permit(:photo))
    redirect_to user_path
  end

  def update  #update
    @user = User.find(params[:id])
    @game = Game.find(params[:game_id])
    @gameslist = ['games', 'games_played', 'games_playing', 'games_want']

    case params[:to]
      when 'games_played'
        @user.games_playing.delete(params[:game_id])
        @user.games_want.delete(params[:game_id])
        @user.games_played << params[:game_id] unless @user.games_played.include? params[:game_id]
      when 'games_want'
        @user.games_playing.delete(params[:game_id])
        @user.games_played.delete(params[:game_id])
        @user.games_want << params[:game_id] unless @user.games_played.include? params[:game_id]
      when 'games_playing'
        @user.games_played.delete(params[:game_id])
        @user.games_want.delete(params[:game_id])
        @user.games_playing << params[:game_id] unless @user.games_played.include? params[:game_id]
    end
      @user.save
      redirect_to user_games_path(@user)
  end

  def games
    @user = current_user
  end

  def reset
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :photo, :password, :password_confirmation)
    end
end

app/views/users/_gamerow.html.erb
<tr class="row game-row">
  <td class="col-md-1">
    <% if game['image'] && game['image']['thumb_url'] %>
      <%= link_to game_path(game) do %>
        <%= image_tag game['image']['thumb_url'], class:"img-thumbnail search-img" %>
      <% end %>
    <% end %>
  </td>
  <td class="col-md-2">
    <%= link_to game['name'], game_path(game) %> 
  </td>
  <td class="col-md-2 showing">
    <%= game.developer %>
  </td>
  <td class="col-md-2 showing">
    <%= game.publisher %>
  </td>
  <td class="col-md-2">
    <b><%= game.average_rating || 'n/a' %></b>
  </td>
  <td class="col-md-2">
    <p>
      <% if my_review(game) %>
        <% (1..my_rating(game)).each do |i| %>
          <%= link_to game_review_path(game, my_review(game), :review => {rating: i}, :from_list => true), :method => :patch, class:'star-group' do %>  
            <span class="glyphicon glyphicon-star on"></span>
          <% end %>
        <% end %>
        <% ((my_rating(game)+1)...6).each do |i| %>
          <%= link_to game_review_path(game, my_review(game), :review => {rating: i}, :from_list => true), :method => :patch, class:'star-group' do %>
            <span class="glyphicon glyphicon-star off"></span>
          <% end %>
        <% end %>
      <% else %>
        <% (1..5).each do |i| %>
          <%= link_to game_reviews_path(game, :review => {rating: i}, :from_list => true), :method => :create, class:'star-group' do %>
            <span class="glyphicon glyphicon-star off"></span>
          <% end %>
        <% end %>
      <% end %>
    </p>
  </td>
  <td class="col-md-1">
    <% if @user.get_list_location(game) && list == :all %>
      <%= @user.get_list_location(game) %>
    <% else %>
      <div class="btn-group-vertical" role="group">
        <% if list == :all || list == :playing || list == :want %>
          <%= button_to user_path(@user, game_id: game.id, to: :games_played), method: :patch, class: 'btn btn-primary btn-block btn' do %>
            <span class="glyphicon glyphicon-plus left"></span> _<small class="right">played</small>
          <% end %>
        <% end %>
        <% if list == :all || list == :played || list == :want %>        
          <%= button_to user_path(@user, game_id: game.id, to: :games_playing), method: :patch, class: 'btn btn-default btn-block btn' do %>
            <span class="glyphicon glyphicon-plus left"></span> _<small class="right">playing</small>
          <% end %>
        <% end %>
        <% if list == :all || list == :playing || list == :played %>
          <%= button_to user_path(@user, game_id: game.id, to: :games_want), method: :patch, class: 'btn btn-success btn-block btn' do %>
            <span class="glyphicon glyphicon-plus left"></span> _<small class="right">to-play</small>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </td>
</tr>

app/views/users/_tableheader.html.erb
<tr class="row">
  <th class="col-md-1">cover</th>
  <th class="col-md-2">title</th>
  <th class="col-md-2 showing">developer</th>
  <th class="col-md-2 showing">publisher</th>
  <th class="col-md-2">avg rating</th>
  <th class="col-md-2">my rating</th>
  <th class="col-md-1">list</th>
</tr>

app/views/users/games.html.erb
<div role="tabpanel">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#all" role="tab" data-toggle="tab" class="list-tab">all <span class="badge"><%= @user.games.count %></span></a></a></li>
    <li role="presentation"><a href="#played" role="tab" data-toggle="tab" class="list-tab"><small>played <span class="badge"><%= @user.games_played.count %></span></small></a></li>
    <li role="presentation"><a href="#current" role="tab" data-toggle="tab" class="list-tab"><small>playing-now <span class="badge"><%= @user.games_playing.count %></span></small></a></li>
    <li role="presentation"><a href="#want" role="tab" data-toggle="tab" class="list-tab"><small>to-play <span class="badge"><%= @user.games_want.count %></span></small></a></li>
  </ul>


<!-- Tab panes -->
  <div class="container-fluid">
    <div class="tab-content">
<!-- All games tab -->
      <div role="tabpanel" class="tab-pane active" id="all">
        <br>
        <table class='table table-striped'>
          <%= render 'users/tableheader' %>
          <% @user.games.reverse.each do |game| %>
            <%= render 'users/gamerow', :game => game, :list => :all %>
          <% end %>
        </table>
      </div>
<!-- Played games tab -->
      <div role="tabpanel" class="tab-pane" id="played">
        <br>
        <table class='table table-striped'>
          <%= render 'users/tableheader' %>
          <% @user.games_played.each do |game_id| %>
            <% game = Game.find(game_id) %>
            <%= render 'users/gamerow', :game => game, :list => :played %>            
          <% end %>    
        </table>  
      </div>
<!-- Currently playing tab -->
      <div role="tabpanel" class="tab-pane" id="current">
        <br>
        <table class='table table-striped'>
          <%= render 'users/tableheader' %>
          <% @user.games_playing.each do |game_id| %>
            <% game = Game.find(game_id) %>
            <%= render 'users/gamerow', :game => game, :list => :playing %>
          <% end %>
        </table>
      </div>
<!-- Want to play tab -->
      <div role="tabpanel" class="tab-pane" id="want">
        <br>
        <table class='table table-striped'>
          <%= render 'users/tableheader' %>
          <% @user.games_want.each do |game_id| %>
            <% game = Game.find(game_id) %>
            <%= render 'users/gamerow', :game => game, :list => :want %>            
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">

  <div class="col-md-1">
  </div>
  <div class="col-md-4">
<h1>Create an account</h1>

<% flash.each do |key, value| %>
  <div class='alert alert-<%= key %>' role='alert'>
    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    <%= value %>
  </div>
<% end %>


<%= form_for @user do |f| %>
  <div class="form-group">
    <p>First name:</p>
    <%= f.text_field :first_name, placeholder:"First name", class: "form-control"%>
  </div>
  <div class="form-group">
    <p>Last name:</p>
    <%= f.text_field :last_name, placeholder:"Last name", class: "form-control"%>
  </div>
  <div class="form-group">
    <p>Email:</p>
    <%= f.text_field :email, placeholder:"Email ", class: "form-control"%>
  </div>
  <div class="form-group">  
    <p>Password:</p>
    <%= f.password_field :password, placeholder:"Choose password", class: "form-control"%>
  </div>
  <div class="form-group">  
    <p>Confirm password:</p>
    <%= f.password_field :password_confirmation, placeholder:"Confirm password", class: "form-control"%>
  </div>
  <div class="form-group">
  <p>Profile pic:</p>
  <%= f.file_field :photo %>
  </div>
  <div class="form-group">
    <%= f.submit "Sign up", class:"btn btn-lg btn-primary" %>
  </div>
<% end %>
</div>
<div class="col-md-7">
</div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="page-header">
    <h2><%= "#{@user.first_name.capitalize} #{@user.last_name.capitalize}'s Profile" %></h2>
    </div>
    <div class="col-md-4">
      <%= image_tag @user.photo, class: "img-thumbnail" %>
      <% if current_user.id == @user.id %>
        <%= form_for @user, url: user_photo_path(@user), method: :patch, class:"form-horizontal" do |f| %>
          <div class='form-group'>
            <%= f.file_field :photo %>
            <%= f.submit "save", class:'btn btn-default btn-xs' %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="col-md-7 well">
      <p><i>Joined in <%= @user.created_at.strftime('%B %Y') %></i></p>
      <p><%= @user.reviews.count %> ratings (<%= @user.average_rating %> avg)</p>
      <p><%= @user.reviews.where(:body.exists => true).count %> reviews</p>
    </div>
  </div>
  <br>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= @user.first_name.capitalize %>'s recently added games</h3>
    </div>
    <div class="panel-body">
      <%= "No games added yet" if @user.games.count == 0 %>
      <% @user.games.order(created_at: :desc).limit(10).each do |game| %>
        <%= link_to game_path(game) do %>
          <%= image_tag game['image']['thumb_url'], class:'img-thumbnail profile-game-img' %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Recent reviews</h3>
    </div>
    <div class="panel-body">
      <%= "No reviews added yet" if @user.reviews.count == 0 %>
      <% @user.reviews.order(created_at: :desc).limit(10).each do |review| %>
        <p>
          <strong><%= review.game.name %></strong> - <small><%= review.created_at.strftime('%B %e, %Y') if review.created_at %></small>
        </p>
        <p>
          <% review.rating.times do %>
             <span class="glyphicon glyphicon-star on"></span>
          <% end %>
          <% (5-review.rating).times do %>
             <span class="glyphicon glyphicon-star off"></span>          
          <% end %>
        </p>
        <p><%= review.title %></p>
        <p><%= review.body %></p>
        <hr>
      <% end %>
    </div>
  </div>

</div>