config/routes.rb
Rails.application.routes.draw do

  #pages
  root "pages#welcome"
  get '/about' => 'pages#about'
  get '/contact' => 'pages#contact'

  #games
  resources :games do
    resources :reviews, only: [:new, :create, :edit, :update]
  end

  #users
  resources :users
  get '/signup' => 'users#new', as: :signup
  get '/users/:id/games' => 'users#games', as: :user_games
  patch '/users/:id/photo' => 'users#photo', as: :user_photo

  #sessions
  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout

  #search
  get '/search' => 'search#results'

  #password resets
  resources :password_resets


end

app/views/pages/about.html.erb
<h1>About</h1>

<div class="well">
WDI Project 2 - GoodGames
<br><br>
This is my second project for the General Assembly WDI course.  It is a website where gamers can add games to collections (like goodreads.com) and can rate and review those games.  
<br><br>
This is a Ruby on Rails application using MongoDB for the database.  The GiantBomb API powers the search and provides all the game data.
<br><br>
The app will be deployed on heroku here:
http://good-games.herokuapp.com/
</div>

app/views/pages/contact.html.erb
<h1>Contact info</h1>

<div class="well">
<p>My name is Rami Burpee.  I am a student in General Assembly's WDI program.</p>
<p>You can find me on <%= link_to "github", "https://github.com/ramijan", target:'_blank' %> or <%= link_to "linkedin", "https://www.linkedin.com/pub/rami-burpee/18/8b8/a56", target:'_blank' %></p>
</div>

app/views/pages/welcome.html.erb
<div class="jumbotron">
  <div class="row center-text">
    <h1>Welcome to GoodGames</h1>
    <p>A community where gamers can keep track of their games and share their ratings and reviews with friends</p>
  </div>
  <br>
  <div class="row center-text">
      <%= link_to "Login", login_path, class:"btn btn-lg btn-success" %>
      <%= link_to "Signup", signup_path, class:"btn btn-lg btn-primary" %>
  </div>
  <br>
  <div class="row center-text">
    <h5>Games recently added by our users:</h5>
    <% Game.all.order(created_at: :desc).limit(5).each do |game| %>
      <%= link_to game_path(game.id) do %>
        <%= image_tag game['image']['thumb_url'], class:"img-thumbnail" %>
      <% end %>
    <% end %>
  </div>
</div>