config/routes.rb
Rails.application.routes.draw do

  #pages
  root "pages#welcome"
  get '/about' => 'pages#about'
  get '/contact' => 'pages#contact'

  #games
  resources :games do
    resources :reviews, only: [:new, :create, :edit, :update]
  end

  #users
  resources :users
  get '/signup' => 'users#new', as: :signup
  get '/users/:id/games' => 'users#games', as: :user_games
  patch '/users/:id/photo' => 'users#photo', as: :user_photo

  #sessions
  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout

  #search
  get '/search' => 'search#results'

  #password resets
  resources :password_resets


end

app/models/game.rb
class Game
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :image, type: Hash
  field :name, type: String
  field :publisher, type: String
  field :developer, type: String
  field :_id, type: String, default: ->{ giant_bomb_game_id }
  field :giant_bomb_game_id, type: String
  
  has_and_belongs_to_many :users
  has_many :reviews

  validates :giant_bomb_game_id, uniqueness: true
  validates_presence_of :name

  def average_rating
    sum = 0
    self.reviews.each do |review|
      sum += review.rating
    end

    if reviews.count > 0
      return (sum.to_f / reviews.count).round(2)
    else
      return nil
    end
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index

  end

  def show
    @game = Game.find(params[:id])
    @review = @game.reviews.find_by(user_id: current_user.id) if current_user && @game
    @gb_data = Giantbomb.game(params[:id])
  end

  def create
    # check if game is already in db
    @game = Game.find_by(giant_bomb_game_id: params[:game_id])

    # if not, get data from giant bomb
    if @game.nil?
      gb_data = Giantbomb.game(params[:game_id])
      @game = Game.create(name: gb_data['name'], 
                          image: gb_data['image'], 
                          developer: (gb_data['developers'][0]['name'] if gb_data['developers']), 
                          publisher: (gb_data['publishers'][0]['name'] if gb_data['publishers']), 
                          giant_bomb_game_id: params[:game_id]
              )
    end

    # push game into user game list
    current_user.games << @game

    # redirect to game details screen
    redirect_to user_games_path(current_user)
  end

end

app/views/games/_reviews.html.erb
<h3>Reviews</h3>
<% if @game %>
  <%= "No reviews yet" if @game.reviews.count == 0 %>
  <% @game.reviews.each do |review| %>
    <div>
      <p> <%= review.rating %>
        <% review.rating.times do %>
          <span class="glyphicon glyphicon-star"></span>
        <% end %>
        <% (5-review.rating).times do %>
          <span class="glyphicon glyphicon-star-empty"></span>          
        <% end %>
        - <%= link_to user_path(review.user) do %>
            <%= review.user.first_name %>
          <% end %>
        - <small><i><%= review.created_at.strftime('%-m/%-e/%y') if review.created_at %></i></small>
      </p>
      <h5><%= review.title %></h5>
      <p><%= review.body %></p>
    </div>
    <hr>
    <br>
  <% end %>
<% end %>

app/views/games/index.html.erb
<div class="row">
  <div class="col-md-5">
  </div>
  <div class="col-md-2">
    PLACEHOLDER <br> for logged in user homepage (recent activity)
  </div>
  <div class="col-md-5">
  </div>
</div>

app/views/games/show.html.erb
<!-- Top section -->
<div class="jumbotron">
  <div class="container-fluid">
  <div class="col-md-3">
    <%= image_tag @gb_data['image']['medium_url'], width:'100%' %>
  </div>
  <div class="col-md-9">
    <h1><%= @gb_data['name'] %></h1>
    <%= @gb_data['publishers'][0]['name'] %>
    <% if @gb_data['original_release_date'] %>
      <h5>Released: <%= @gb_data['original_release_date'].to_datetime.strftime('%B %e, %Y') %></h5>
    <% else %>
      <h5>Release date: <%= "#{@gb_data['expected_release_month']} / #{@gb_data['expected_release_day']}" || @gb_data['expected_release_quarter'] %> / <%= @gb_data['expected_release_year'] %></h5>
    <% end %>
    <%= render 'stardisplay' %>


    <p>
      <small><%= @gb_data['platforms'].map {|i| i['abbreviation']}.join(' / ') if @gb_data['platforms'] %></small>
    </p>
    <h4><%= @gb_data['deck']  %></h4>
    <% if current_user %>
      <% if @game && current_user.games.find(@game.id) %>
        <% if @review %>
          <%= link_to "Edit your Review", edit_game_review_path(@game, @review), class:"btn btn-lg btn-primary" %>
        <% else %>
          <%= link_to "Write a Review", new_game_review_path(@game), class:"btn btn-lg btn-primary" %>
        <% end %>
      <% else %>
        <%= link_to "Add to collection", games_path(game_id:get_id(@gb_data)), :method => :post, class:"btn btn-lg btn-primary" %>
      <% end %>
    <% end %>
  </div>
  </div>
</div>

<!-- Bottom section -->
<div class="row">
  <!-- Giant bomb data -->
  <div class="col-md-8">
    <div role="tabpanel">

      <!-- Nav tabs -->
      <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#details" role="tab" data-toggle="tab">Details</a></li>
        <li role="presentation"><a href="#videos" role="tab" data-toggle="tab">Videos</a></li>
        <li role="presentation"><a href="#images" role="tab" data-toggle="tab">Images</a></li>
        <li role="presentation"><a href="#reviews" role="tab" data-toggle="tab" class="hiding">Reviews</a></li>
      </ul>

      <!-- Tab panes -->
      <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="details">
          <%= raw @gb_data['description'] %>
        </div>
        <div role="tabpanel" class="tab-pane" id="videos">
          <br>
          <% @gb_data['videos'].each do |vid| %>
            <%= link_to vid['site_detail_url'] do %>
              <p><%= vid['name'] %></p>
            <% end %>
          <% end %>
        </div>
        <div role="tabpanel" class="tab-pane" id="images">
          <br>
          <% @gb_data['images'].each do |img| %>
            <%= image_tag img['thumb_url'], class:'img-thumbnail images' %>
          <% end %>
        </div>
        <div role="tabpanel" class="tab-pane" id="reviews">
          <%= render 'games/reviews' %>
        </div>
      </div>
    </div>
  </div>
  <!-- Reviews -->
  <div class="col-md-4 well showing">
    <%= render 'games/reviews' %>
  </div>
</div>