config/routes.rb
Rails.application.routes.draw do

  #pages
  root "pages#welcome"
  get '/about' => 'pages#about'
  get '/contact' => 'pages#contact'

  #games
  resources :games do
    resources :reviews, only: [:new, :create, :edit, :update]
  end

  #users
  resources :users
  get '/signup' => 'users#new', as: :signup
  get '/users/:id/games' => 'users#games', as: :user_games
  patch '/users/:id/photo' => 'users#photo', as: :user_photo

  #sessions
  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout

  #search
  get '/search' => 'search#results'

  #password resets
  resources :password_resets


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    flash[:warning] = "You must be logged in to access that content"
    redirect_to login_path unless current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def get_id(game)
    game['api_detail_url'].match(/\d+-\d+/).to_s
  end

    #helper for displaying star ratings in games.html.erb
  def my_rating(game)
    review = current_user.reviews.find_by(game_id: game.id)
    if review
      return review.rating
    else
      return 0
    end
  end

  def my_review(game)
    return current_user.reviews.find_by(game_id: game.id)
  end

end

app/views/application/_footer.html.erb
<nav class="navbar navbar-default navbar-inverse footer">
  <div class="row">
    <div class="col-xs-6">
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "About", about_path, class:'navbar-link' %></li>
        <li><%= link_to "Contact", contact_path, class:'navbar-link' %></li>
      </ul>
    </div>
    <div class="col-xs-6 gb-logo">
        <%= link_to 'http://www.giantbomb.com', target:'_blank' do %>
          <p class="navbar-link"> Powered by: 
            <%= image_tag 'giant-bomb-logo.png', height:'40' %>
          </p>
        <% end %>
    </div>
  </div>
</nav>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-default navbar-inverse">
    <div class="navbar-header">
      <%= link_to root_path, class:'navbar-brand' do %>
        <span class="big">G</span>ood<span class="big">G</span>ames
      <% end %>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
 <div class="collapse navbar-collapse" id="nav-collapse">
<ul class="nav navbar-nav navbar-right">
  <li>
    <%= form_tag search_path, method: :get, class:"navbar-form showing" do %>
    <div class="form-group">
      <%= text_field_tag :query, nil, placeholder:"Search", class:"form-control search-bar" %>
      <%= button_tag class:"btn btn-link search-button" do %>
        <span class="glyphicon glyphicon-search"></span>
      <% end %>
    </div>
    <% end %>
  </li>
  <li>
    <% if current_user %>
      <%= link_to user_games_path(current_user), class:'navbar-link' do %>
        My Games (<%= current_user.games.count %>)
      <% end %>
    <% end %>    
  </li>
  <% if current_user %>
    <li class="dropdown">
      <%= link_to "#{current_user.email}", user_path(current_user), class:"navbar-link float-left" %>
      <a href="#" class="dropdown-toggle float-right" data-toggle="dropdown" role="button">
        <span class="caret"></span>
      </a>
      <ul class="dropdown-menu" role="menu">
        <li><%= link_to "Logout", logout_path %></li>
      </ul>
    </li>
  <% else %>
    <li>
      <%= link_to "Login", login_path, class:"navbar-link" %> 
    </li>
    <li>
      <%= link_to "Sign up", signup_path, class:"navbar-link right" %>
    </li>
  <% end %>
  </ul>
  </div>
</nav>

<%= form_tag search_path, method: :get, class:"form-horizontal hiding" do %>
  <div class="input-group">
    <%= text_field_tag :query, nil, placeholder:"Search", class:"form-control search-bar" %>
    <div class="input-group-btn">
    <%= button_tag class:"btn btn-primary search-button" do %>
      <span class="glyphicon glyphicon-search"></span>
    <% end %>
    </div>
  </div>
  <br>
<% end %>

app/views/application/_stardisplay.html.erb
<div>
  <% if @game && @game.average_rating %>
    <% (1..@game.average_rating.floor).each do |i| %>
        <span class="glyphicon glyphicon-star on"></span>
    <% end %>
    <% ((@game.average_rating.floor+1)...6).each do |i| %>
        <span class="glyphicon glyphicon-star off"></span>
    <% end %>
    <small><%= "- (#{@game.average_rating} avg) based on #{@game.reviews.count} reviews" %></small>
  <% else %>
    <% (1..5).each do |i| %>
        <span class="glyphicon glyphicon-star off"></span>
    <% end %>
    <small>- no ratings yet</small>
  <% end %>
</div>